# Btop everforest dark hard theme by u/archontop.

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#282828"

# Main text color
theme[main_fg]="#fbf1c7"

# Title color for boxes
theme[title]="#fbf1c7"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#d3869b"

# Background color of selected items
theme[selected_bg]="#665c54"

# Foreground color of selected items
theme[selected_fg]="#fabd3f"

# Color of inactive/disabled text
theme[inactive_fg]="#282828"  

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#fbf1c7"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#83a598"

# Cpu box outline color
theme[cpu_box]="#665c54"

# Memory/disks box outline color
theme[mem_box]="#665c54"

# Net up/down box outline color
theme[net_box]="#665c54"

# Processes box outline color
theme[proc_box]="#665c54"

# Box divider line and small boxes line color
theme[div_line]="#665c54"

# Temperature graph colors
theme[temp_start]="#8ec07c"
theme[temp_mid]="#83a598"
theme[temp_end]="#d3869b"

# CPU graph colors
theme[cpu_start]="#8ec07c"
theme[cpu_mid]="#83a598"
theme[cpu_end]="#d3869b"

# Mem/Disk free meter
theme[free_start]="#d3869b"
theme[free_mid]="#83a598"
theme[free_end]="#8ec07c"

# Mem/Disk cached meter
theme[cached_start]="#83a598"
theme[cached_mid]="#8ec07c"
theme[cached_end]="#b8bb26"

# Mem/Disk available meter
theme[available_start]="#d3869b"
theme[available_mid]="#83a598"
theme[available_end]="#8ec07c"

# Mem/Disk used meter
theme[used_start]="#8ec07c"
theme[used_mid]="#83a598"
theme[used_end]="#d3869b"

# Download graph colors
theme[download_start]="#8ec07c"
theme[download_mid]="#83a598"
theme[download_end]="#d3869b"

# Upload graph colors
theme[upload_start]="#d3869b"
theme[upload_mid]="#83a598"
theme[upload_end]="#8ec07c"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#8ec07c"
theme[process_mid]="#d3869b"
theme[process_end]="#fb4934"
